import Head from 'next/head'
import Image from 'next/image'
import LpUser from '../components/LpUser'
import NavbarUser from '../components/NavbarUser'
import Footer from '../components/Footer'
import FooterCP from '../components/FooterCP'

export default function LandingPagesUser() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavbarUser/>
        <LpUser/>
        <Footer/>
        <FooterCP/>
    </div>
  )
}
