import Head from 'next/head'
import Image from 'next/image'
import LoginForm from '../components/LoginForm'

export default function Login() {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <LoginForm/>
    </div>
  )
}
