import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import FooterCP from '../components/FooterCP'
import MainMateri2 from '../components/MainMateri2'
import NavbarUser from '../components/NavbarUser'



export default function MateriSlide() {
  return (
    <div>
      <Head>
        <title>MateriNext</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarUser/>
    <MainMateri2/>
    <Footer/>
    <FooterCP/>
    </div>
  )
}