import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import FooterCP from '../components/FooterCP'
import NavbarUser from '../components/NavbarUser'
import Mclass from '../components/Mclass'


export default function MyClass() {
  return (
    <div>
      <Head>
        <title>MyClass</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarUser/>
      <Mclass/>
      <Footer/>
      <FooterCP/>
    </div>
  )
}