import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import FooterCP from '../components/FooterCP'
import NavbarUser from '../components/NavbarUser'
import Mcourse from '../components/Mcourse'


export default function MyCourse() {
  return (
    <div>
      <Head>
        <title>MyCourse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarUser/>
      <Mcourse/>
      <Footer/>
      <FooterCP/>
    </div>
  )
}
