import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import FooterCP from '../components/FooterCP'
import NavbarUser from '../components/NavbarUser'
import Progress from '../components/Progress'



export default function MyProgress() {
  return (
    <div>
      <Head>
        <title>MyProgress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarUser/>
    <Progress/>
    <Footer/>
    <FooterCP/>
    </div>
  )
}