import Head from 'next/head'
import NavbarUser from '../components/NavbarUser'
import Footer from '../components/Footer'
import FooterCP from '../components/FooterCP'
import Statistik from '../components/Statistik'

export default function MyStatistik() {
  return (
    <div>
      <Head>
        <title>My Statistik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NavbarUser/>
        <Statistik/>
        <Footer/>
        <FooterCP/>
    </div>
  )
}
