import Head from 'next/head'
import Image from 'next/image'
import Setting1 from '../components/Setting1'
import NavbarUser from '../components/NavbarUser'



export default function Settings() {
  return (
    <div>
      <Head>
        <title>Settings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavbarUser/>
        <Setting1/>
    </div>
  )
}
